final_code/artgame/artgame/urls.py
# this is the artgame/urls.py

"""artgame URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.index, name='index'), 
    path('', include('game.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_code/artgame/game/urls.py
# this is the game/urls.py

from django.contrib.auth import views as auth_views

from django.urls import path, include
from game import views

# Define application name
app_name = 'game'

# Define URL links such that path(link, associated views method, name)
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('initgame/', views.initgame, name='initgame'),
    path('game/', views.game, name='game'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
]

final_code/artgame/game/forms.py
from django import forms

# give us base use class
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from .models import Keyword

# User Registration Form
class RegisterForm(forms.ModelForm):

  # username field
  username = forms.CharField(max_length=30, required=True, help_text='Use your Lafayette username.')

  # password field but  hide the password the user inputting
  password = forms.CharField(max_length=30, required=True, help_text='Choose wisely.', widget=forms.PasswordInput)

  # email field
  email = forms.EmailField(max_length=254, required=True, help_text='Use your Lafayette email.')

  # information about our class
  class Meta:
    model = User
    fields = ['username', 'email', 'password']

# Keyword Input Form
class KeywordForm(forms.Form):

    # keyword field
    k_text = forms.CharField(label='Keyword:', max_length=50, required=True, validators=[RegexValidator('^[a-zA-Z]+$')])

    # Method that pulls the input keyword and returns a cleaned copy
    def clean_k_text(self):
      data = self.cleaned_data['k_text']
      return data.lower()

final_code/artgame/game/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm, KeywordForm
from .models import Artwork, Player, Keyword, PlayerWord, Category
from .bad_words import bad_word_list

# View function that renders the home page
def index(request):
  return render(request, 'game/home.html')

# View function that renders the about page
def about(request):
  return render(request, 'game/about.html')

# View function that handles requests for user profile
def profile(request):
  p = Player.objects.get(username=request.user.username)
  return render(request, 'game/profile.html', locals())

# View function that pulls the list of players and sends it to the rendering of the leaderboard page
def leaderboard(request):

  # Pull the list of all players registered in the database
  player_list = Player.objects.all()
  player_list = player_list[:10]

  # Send the list of all players to render in the leaderboard page
  return render(request, 'game/leaderboard.html', locals())


def initgame(request):
    if request.user.is_authenticated:
        
        p = Player.objects.get(username=request.user.username)
        p.newGame()
        request.session['error_flag'] = 0
        if request.method == 'POST':
          c = request.POST.get('category', False)
          if c is "":
            pass
          elif int(c) != -1 :
            p.setCategory(int(c))
            return HttpResponseRedirect('/game/')
        p.setCategoryNull()
        return HttpResponseRedirect('/game/')
    return HttpResponseRedirect('/')


# View function that handles game functionality
def game(request):

    # If the request is coming from a user that is logged in
    if request.user.is_authenticated:

        p = Player.objects.get(username=request.user.username)
        c_list = Category.getCategoryList()

        # Load the next artwork that the player should label
        img = p.next_art
        t = p.curr_timer

        #if POST request, then the data was just submitted to form
        if request.method == 'POST':
            error_flag = 0
            # Load the keyword form
            k_form = KeywordForm(request.POST)
            t = request.POST.get('timer', False)

            if int(t) == 0:
                p.finishImage()
            else:

                #update players time remaining
                p.setTime(t)

                # If the keyword form is valid
                if k_form.is_valid():
                    word = k_form.cleaned_data.get('k_text')

                    # If the word is not a bad word
                    if (not checkWord(word)):

                        # If the player has not already provided this word for the image
                        if (not PlayerWord.check_dup(word, p)):

                            # Submit the word to the database and return the score
                            x = p.submitWord_getScore(word, img) 

                        # If the Player has already provided this word for this image
                        else: error_flag=1
                        # If the word is a bad word
                    else: error_flag=2
                else: error_flag=3

            # If the form is not valid, redirect back to the game
            request.session['error_flag'] = error_flag
            return redirect('/game/')

        
        error_flag = request.session.get('error_flag')
        #print(error_flag)
        # If not POST request, render empty form, image for input
        k_form = KeywordForm()

        # Put the submitted words
        p_words = PlayerWord.getWords(p)
        height = int((350.0/float(img.artwork_image.width))*img.artwork_image.height) 

        # Render the game view passing in the image, the keyword form and the list of labes
        return render(request, 'game/game.html', {'image': img, 'k_form': k_form, 'p_words': p_words, 'curr_time': t, 'p': p, 'c_list': c_list, 'height': height, 'error_flag': error_flag})

    # If the user is not authenticated, redirect is to home page
    else:
      return HttpResponseRedirect('/')
    #if HttpRequest.is_ajax():

# View function that checks is a submitted label is considered innapropriate
def checkWord(word):

  # List of unacceptable words
  
  # if the word is in the list, return true
  if word in bad_word_list:
    return True

  # if the word is not in the list, return false
  else:
    return False


def descriptor(request):
  form = DescriptorForm(request.POST or None)
  if form.is_valid():
    keyword = form.save(commit=False)
    descriptor = form.cleaned_data.get('descriptor')
    Keyword.addKeyword(descriptor)
    if keyword is not None:
      return render(request, 'game/game.html', {'form': form})
  return render(request, 'game/game.html', {'form': form})

# View function that handles user registration
def register(request):

  # Load in the user registration form
  form = RegisterForm(request.POST or None)

  # If the form is valid
  if form.is_valid():

    # Save the form
    user = form.save(commit=False)

    # Extract username and password
    username = form.cleaned_data.get('username')
    password = form.cleaned_data.get('password')

    # Associate the indicated password with the user
    user.set_password(password)

    # Save the user
    user.save()

    # Add the newly register user to the Player table
    Player.addPlayer(username)
    user = authenticate(username=username, password=password)

    # If the user is not empty
    if user is not None:

      # If the user already has an account
      if user.is_active:

        # Login the user and redirect them to game
        login(request, user)
        return HttpResponseRedirect('/initgame/')

  # Once a user is registered, send them to game portal
  return render(request, 'game/register.html', {'form': form})

final_code/artgame/game/templates/game/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'game/style.css' %}" />

<div id="container">
  {% if user.is_authenticated %}

    <nav class="topnav">
       <a class="active" href="/"> Home </a>
       <a class="active" href="{% url 'game:initgame' %}"> Game </a>
       <a class="active" href="{% url 'game:leaderboard' %}"> Leaderboard </a>
       <a class="active" href="{% url 'game:about' %}"> About </a>     
       <div class="dropdown">
         <button class="dropbtn"> {{user.username}} 
           <i class="fa fa-caret-down"></i>
         </button>
        <div class="dropdown-content">
         <a href="{% url 'game:profile' %}">Profile</a>
         <a href="/accounts/logout"> Logout </a> 
        </div>
       </div>       
    </nav>

  {% else %}

    <nav class="topnav">
       <a class="active" href="/"> Home </a>
       <a class="active" href="{% url 'game:leaderboard' %}"> Leaderboard </a>
       <a class="active" href="{% url 'game:about' %}"> About </a>
       <a class="active" href="/accounts/login"> Signup/Login </a>
    </nav>

  {% endif %} 

  <body>
    <div id="body">
      {% block body %}
      {% endblock %}
    </div>
  </body>
 
  <div id="footer">
    <footer>
      <p color="white"> Owned and operated by Lafayette College </p>
    </footer>
  </div>
</div>

final_code/artgame/game/templates/game/game.html
{% extends "game/base.html" %}

 <head>
   <script src="http://code.jquery.com/jquery-3.3.1.js"></script>
  </head>

{% block body %}

<div class="gamebox"> 
  
  <h1> Welcome to the Lafayette Image Labeling Game! </h1>
 	
  <h3 align="center" color="black"> 
        For each image displayed, generate relevant labels inside the text box and hit the "Submit" 
        button or the ENTER key on your keyboard. You have 60 seconds for each image. Points will be
	      awarded to you depending on the relevance of your generated label, this will be displayed in the label box on the left hand side of the screen. If you would like to label a certain artist, choose the artist from the dropdown menu on the right hand side fo the page and that artists photographs will be displayed to you. 
  </h3> 
  <!-- We need to take the timeRemaining variable and save it to the appropriate model   -->
  
  <h3> Seconds Remaining: <var id="timeRemaining"> {{curr_time}} </var> </h3>

  <img id="artwork" border="black" width="350" height="{{ height }}" src="{{ image.artwork_image.url }}"> 
 
  {% if error_flag == 1 %}
    <h3 id="badword"> Duplicate keyword </h3>
  {% elif error_flag == 2 %}
    <h3 id="badword"> Unsavory keyword </h3>
  {% elif error_flag == 3 %}
    <h3 id="badword"> Space or numbers in keyword </h3>
  {% endif %}

  <textarea id = "myTextArea" rows ="20" cols= "40" readonly>  
    {% for PlayerWord in p_words %}
      {{ PlayerWord.word }} {{ PlayerWord.pts }}
    {% endfor %}
  </textarea>
 
  <h3 id="playerStats"> Total Score: {{ p.total_score }} </h3> 
  <h3 id="playerCurr"> Current Score: {{ p.curr_score }} </h3>

  <form id="keywordForm" name="keywordForm" action="/game/" method="post">
    {% csrf_token %}
    {{ k_form }}
    <input type="hidden" value="" id="timer" name="timer">
    <button type="submit" onclick="submitTime();"> Submit </button>  
  </form>
  
  <h3 id="artistLabel"> Choose Category: </h3>
  <form id="catForm" name="catForm" action="/initgame/" method="post">
    {% csrf_token %}
    <select name="category" id="category" onchange="this.form.submit()">
      {% for c in c_list %}
        <option value="{{c.id}}"
        {% if p.category == c %} selected {% endif %}>
         {{ c.category_name }} <option>
      {% endfor %}
      <option value="-1"
      {% if p.category is None %} selected {% endif %}> 
      None <option>
    </select> 

  </form>


<script>
    var CCOUNT = {{curr_time}};    
    var t, count, loop;
    
    window.onload = function() {
      //var selectInput = document.getElementById("keywordInput");
      //selectInput.focus();
      //selectInput.select();
      beginTimer();
    }

    window.onbeforeunload = function() {
      
    }
    
    function beginTimer(){
        cdreset();
        countdown();
    }
    
    function cddisplay() {
        // displays time and loop in span
        document.getElementById("timeRemaining").innerHTML = count;
    };
    
    function countdown() {
        // starts countdown
        cddisplay();

        // if you hit zero, reset the timer to 60
        if (count == 0) {
            document.keywordForm.timer.value = count;
            document.forms["keywordForm"].submit();            
        // otherwise just continue to count down
        } else {
            count--;
            t = setTimeout("countdown()", 1000);
        }
    };
    
    function cdpause() {
        // pauses javascript timer, but not countdown
        clearTimeout(t);
    };
    
    function cdreset() {
        // resets countdown, resets bot count and loop
        cdpause();
        count = CCOUNT;
        loop = 1;
        cddisplay();
    };

    function submitTime(){
      document.keywordForm.timer.value = count;
      document.forms["keywordForm"].submit();
    }

    

    

</script>
</div> 

{% endblock %}
	

final_code/artgame/game/templates/game/home.html
{% extends "game/base.html" %}

{% block body %}
	<h1> Welcome to Lafayette College Art Game! </h1>
	<h2 align="center"> 
		This is a project coordinated by the Lafayette College Computer Science Department. <br> 
		To access the game portal, please create an account or login to an existing account. 
	</h2>

	<img class="resize" align="middle" src="/static/game/cover_image.jpg" alt="example image">

{% endblock %}

final_code/artgame/game/templates/game/leaderboard.html
{% extends "game/base.html" %}

{% block body %}

<h1> Current Leaderboard </h1>
<h4> These are the top 10 players in the game. </h4>

<table align="center">
  <tr>
    <th>Rank</th>
    <th>Username</th>
    <th>Max Game</th>
    <th>Total Score</th>
  </tr>	
  {% for Player in player_list %}
  <tr>
    <td>{{forloop.counter}}</td>
  	<td>{{Player.username}}</td>
  	<td>{{Player.high_score}}</td>
  	<td>{{Player.total_score}}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

final_code/artgame/game/templates/game/profile.html
{% extends "game/base.html" %}

{% block body %}

  {% if user.is_authenticated %}
  <div class="transbox"> 
    <h1> Hello, {{ p.username }}! </h1>
    <h2> Your total score is: {{p.total_score}} </h2>
    <h2> Your single game high score is: {{p.high_score}} </h2>
    <h2> You have played: {{p.games_played}} games</h2>
  </div>
  {% else %}
    <h1> Please login to access your user profile or create an account </h1>
    <a href="{% url 'login' %}
  {% endif %}
{% endblock %}

final_code/artgame/game/templates/game/register.html
{% extends "game/base.html" %} 

{% block body %}
  <h1 color="black">New User? Sign Up! </h1>

  <form style="color:black" method="post">
    {% csrf_token %}
    {% for field in form %}
      <p style="color:black">
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up!</button>
  </form>

{% endblock %}